Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.hostname = "node1"
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 512
        vb.gui = false
    end
end